Add browserify-shim to deps instead of dev-deps
I installed react-ghost-i18n with `npm install --save react-ghost-i18n`, and I got the error:

    15 02 2016 11:17:42.717:ERROR [framework.browserify]: Error: Cannot find module 'browserify-shim' from '…/node_modules/react-ghost-i18n'

I figured out that `browserify-shim` was not installed automatically by the package.
Adding it to `dependencies` fixes the problem.
However, maybe it should be added to `peerDependencies` instead?